<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-5BQ0K9K" ignored="0" name="Test" tests="7" failures="1" timestamp="08 Apr 2018 19:42:17 GMT" time="43.47" errors="0">
  <testcase name="loginTest" time="2.622" classname="testCases.TestCases"/>
  <testcase name="openConversionTrackersTest" time="0.585" classname="testCases.TestCases"/>
  <testcase name="verifyConversionTrackersViewContent" time="1.399" classname="testCases.TestCases"/>
  <testcase name="openCreateConversionTrackerModal" time="0.379" classname="testCases.TestCases"/>
  <testcase name="verifyConversionTrackerModal" time="0.835" classname="testCases.TestCases"/>
  <testcase name="verifyMandatoryFields" time="4.502" classname="testCases.TestCases"/>
  <testcase name="addNewConversionTracker" time="1.385" classname="testCases.TestCases">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at testCases.TestCases.addNewConversionTracker(TestCases.java:184)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- addNewConversionTracker -->
</testsuite> <!-- Test -->
